### PR TITLE
Add Group Relationship Model

### PR DESCRIPTION
**Pull request by han-so1omon**
From Miro: https://miro.com/app/board/uXjVOoYi1iA=/?share_link_id=196675780353

Inspired by Kubernetes governance diagram: https://github.com/kubernetes/community/blob/master/kubernetes_governance_diagram.png

Signed-off-by: Eric Solomon <eric@icon.foundation>

### CODE REVIEW

**Comment by CyrusVorwald-ICON** [comment]
This relationship model outlines the decision escalation path of various groups, but we currently do not have any of these groups. So far, I can see the ICON Foundation as a technical steering committee and a BTP working group. I think we need to start with only what we have activity to support, and grow this framework as the ecosystem grows. This would mean first defining special interest group, working group, and steering committees.

**Comment by han-so1omon** [comment]
@CyrusVorwald-ICON This relationship model must be agreed upon so that all groups to come can be placed into the correct scope. I am adding the technical steering committee to this PR, which would be the first group defined

**Review by CyrusVorwald-ICON — APPROVED** [review]

**Review by CyrusVorwald-ICON — CHANGES_REQUESTED** [review]
We should further discuss the group relationship diagram. I don't think it fits our current setup very well because there are no working groups and I don't anticipate there will be for some time.

**Comment by CyrusVorwald-ICON** [comment]
Closing this pull request as I want to use tacklebox to generate our docs to better support our community members efforts. Also, our conventions are not going to strictly follow kubernetes.

**Comment by CyrusVorwald-ICON** [comment]
I also already merged the group relationship model diagram to main independently of this by accident and don't think it warrants undoing history.

**Pull request closed without merging**
